nome = input('Qual é o seu nome? ')
print(f'Seu nome é: {nome}.')
altura = input('Qual é sua altura? ')
print(f'Sua altura é: {altura}')
quilos = input('Quantos quilos você tem? ')
print(f'Você pesa {quilos}kg.')
a = float(altura)
q = int(quilos)
imc = q / (a * a)
print(f'Seu imc é: {imc:.2f}.')